#!/usr/bin/env python3
"""Scan the repository and build REPO_MAP.md with content depth analysis."""
import os
import re
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
SYSTEM_DIR = REPO_ROOT / "_SYSTEM"

def count_words(text):
    """Count non-empty words in text."""
    return len(text.split())

def count_headings(text):
    """Count markdown headings."""
    return len(re.findall(r'^#{1,6}\s', text, re.MULTILINE))

def count_links(text):
    """Count internal markdown links."""
    return len(re.findall(r'\[([^\]]*)\]\(([^)]+)\)', text))

def has_substantial_content(filepath):
    """Check if file has real study content vs just links/index."""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            text = f.read()
    except:
        return False
    
    words = count_words(text)
    headings = count_headings(text)
    links = count_links(text)
    
    # Classify content depth
    if words < 50:
        return 'EMPTY'
    elif words < 200 and headings < 3:
        return 'INDEX_ONLY'
    elif words < 500:
        return 'THIN'
    else:
        return 'HAS_CONTENT'

def classify_status(filepath, rel_path):
    """Classify file status based on content analysis."""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            text = f.read()
    except:
        return 'UNKNOWN', 0, 0, 0
    
    words = count_words(text)
    headings = count_headings(text)
    links = count_links(text)
    
    # Check for placeholder content
    placeholders = ['coming soon', 'todo', 'study here', 'more questions later', 
                    'placeholder', 'fill in', 'add content']
    has_placeholder = any(p in text.lower() for p in placeholders)
    
    if has_placeholder and words < 300:
        status = 'PLACEHOLDER'
    elif words < 50:
        status = 'EMPTY'
    elif words < 150 and headings < 2:
        status = 'INDEX_ONLY'
    elif words < 500:
        status = 'THIN'
    elif words < 1500:
        status = 'PARTIAL'
    else:
        status = 'SUBSTANTIAL'
    
    return status, words, headings, links

def get_domain_from_path(rel_path):
    """Extract domain/track from path."""
    parts = Path(rel_path).parts
    if len(parts) < 2:
        return 'ROOT'
    
    if parts[0] == 'core':
        if len(parts) >= 2:
            return f"CORE/{parts[1].upper()}"
    elif parts[0] == 'non-core':
        if len(parts) >= 2:
            return f"NON-CORE/{parts[1].upper()}"
    elif parts[0] == 'prep':
        if len(parts) >= 2:
            return f"PREP/{parts[1].upper()}"
    elif parts[0] == 'questions':
        return 'QUESTIONS'
    elif parts[0] == 'resources':
        return 'RESOURCES'
    elif parts[0] == 'software-and-tech':
        return 'SOFTWARE-TECH'
    elif parts[0] == 'index':
        return 'INDEX'
    elif parts[0] == 'docs':
        return 'DOCS'
    
    return parts[0].upper()

def main():
    results = []
    
    for root, dirs, files in os.walk(REPO_ROOT):
        # Skip _SYSTEM, .git, .github
        rel_root = os.path.relpath(root, REPO_ROOT)
        if rel_root.startswith('_SYSTEM') or rel_root.startswith('.git') or rel_root.startswith('.github'):
            continue
        if '.git' in dirs:
            dirs.remove('.git')
        
        for f in sorted(files):
            if not f.endswith('.md'):
                continue
            
            filepath = os.path.join(root, f)
            rel_path = os.path.relpath(filepath, REPO_ROOT)
            
            status, words, headings, links = classify_status(filepath, rel_path)
            domain = get_domain_from_path(rel_path)
            
            results.append({
                'path': rel_path,
                'domain': domain,
                'status': status,
                'words': words,
                'headings': headings,
                'links': links,
            })
    
    # Sort by domain then path
    results.sort(key=lambda x: (x['domain'], x['path']))
    
    # Generate REPO_MAP.md
    lines = []
    lines.append("# REPO_MAP.md — Repository Content Inventory")
    lines.append("")
    lines.append(f"Generated by build_repo_map.py")
    lines.append(f"Total markdown files: {len(results)}")
    lines.append("")
    
    # Summary stats
    status_counts = {}
    domain_counts = {}
    for r in results:
        status_counts[r['status']] = status_counts.get(r['status'], 0) + 1
        domain_counts[r['domain']] = domain_counts.get(r['domain'], 0) + 1
    
    lines.append("## Status Summary")
    lines.append("")
    for status in ['SUBSTANTIAL', 'PARTIAL', 'THIN', 'INDEX_ONLY', 'EMPTY', 'PLACEHOLDER', 'UNKNOWN']:
        count = status_counts.get(status, 0)
        if count > 0:
            lines.append(f"- **{status}**: {count}")
    lines.append("")
    
    lines.append("## Domain Summary")
    lines.append("")
    for domain in sorted(domain_counts.keys()):
        lines.append(f"- **{domain}**: {domain_counts[domain]} files")
    lines.append("")
    
    lines.append("## Detailed Inventory")
    lines.append("")
    lines.append("| Path | Domain | Status | Words | Headings | Links |")
    lines.append("|------|--------|--------|------:|---------:|------:|")
    
    current_domain = None
    for r in results:
        if r['domain'] != current_domain:
            current_domain = r['domain']
            lines.append(f"| **{current_domain}** | | | | | |")
        
        status_icon = {
            'SUBSTANTIAL': '✓',
            'PARTIAL': '△',
            'THIN': '◦',
            'INDEX_ONLY': '○',
            'EMPTY': '✗',
            'PLACEHOLDER': '⚠',
            'UNKNOWN': '?'
        }.get(r['status'], '?')
        
        lines.append(f"| {r['path']} | {r['domain']} | {status_icon} {r['status']} | {r['words']} | {r['headings']} | {r['links']} |")
    
    output = '\n'.join(lines)
    
    # Write REPO_MAP.md
    with open(SYSTEM_DIR / 'REPO_MAP.md', 'w', encoding='utf-8') as f:
        f.write(output)
    
    # Print summary
    print(f"=== REPO MAP GENERATED ===")
    print(f"Total files: {len(results)}")
    print(f"Status breakdown:")
    for status in ['SUBSTANTIAL', 'PARTIAL', 'THIN', 'INDEX_ONLY', 'EMPTY', 'PLACEHOLDER']:
        count = status_counts.get(status, 0)
        if count > 0:
            print(f"  {status}: {count}")
    print(f"\nDomain breakdown:")
    for domain in sorted(domain_counts.keys()):
        print(f"  {domain}: {domain_counts[domain]}")
    
    # Identify P0 gaps (EMPTY/PLACEHOLDER in important domains)
    print(f"\n=== P0 GAPS (EMPTY/PLACEHOLDER) ===")
    for r in results:
        if r['status'] in ('EMPTY', 'PLACEHOLDER'):
            print(f"  [{r['domain']}] {r['path']}")
    
    print(f"\n=== THIN FILES (< 500 words, need enrichment) ===")
    thin_count = 0
    for r in results:
        if r['status'] == 'THIN':
            thin_count += 1
            print(f"  [{r['domain']}] {r['path']} ({r['words']} words)")
    print(f"  Total thin: {thin_count}")
    
    print(f"\n=== INDEX_ONLY FILES (links only, no study content) ===")
    idx_count = 0
    for r in results:
        if r['status'] == 'INDEX_ONLY':
            idx_count += 1
            print(f"  [{r['domain']}] {r['path']}")
    print(f"  Total index-only: {idx_count}")

if __name__ == '__main__':
    main()
